---
title: "spam-classification-kamryn"
author: "kamryn"
date: "2024-11-14"
output: html_document
---

```{r}
spam_data <- read.table(file = here("C:\\Users\\kamry\\OneDrive\\Documents\\DS400\\SMSSpamCollection"), sep = "\t", quote = "", comment.char = "")
```

```{r}
colnames(spam_data)

```

```{r}
library(tidytext)
library(dplyr)

spam_text <- spam_data %>%
  filter(V1 == "spam")

bigram_counts <- spam_text %>%
  unnest_tokens(bigram, V2, token = "ngrams", n = 2) %>%
  separate(bigram, into = c("word1", "word2"), sep = " ") %>%
  filter(!is.na(word1) & !is.na(word2)) %>%
  count(word1, word2, sort = TRUE)

bigram_counts <- bigrams %>%
  separate(bigram, into = c("word1", "word2"), sep = " ") %>%
  filter(!is.na(word1) & !is.na(word2))

top_bigrams <- bigram_counts %>%
  mutate(bigram = paste(word1, word2, sep = " ")) %>%
  top_n(15, n) %>%
  arrange(n)

top_bigrams %>%
  ggplot(aes(x = reorder(bigram, n), y = n)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(title = "Top 15 Bigrams", x = "Bigram", y = "Frequency") +
  coord_flip() +
  theme_minimal()

```
